version: "3.8"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]
